In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
columns = ['Season', 'Age', 'Childish diseases', 'Accident or Trauma', 'Surgical Intervention', 'High fevers in last year', 'Frequency of alcohol consumption', 'Smoking habit', 'Number of hours spent sitting per day', 'Output']

df = pd.read_csv('fertility_Diagnosis.txt', names=columns)

df

Season   Age  Childish diseases  Accident or Trauma  \
0    -0.33  0.69                  0                   1   
1    -0.33  0.94                  1                   0   
2    -0.33  0.50                  1                   0   
3    -0.33  0.75                  0                   1   
4    -0.33  0.67                  1                   1   
..     ...   ...                ...                 ...   
95   -1.00  0.67                  1                   0   
96   -1.00  0.61                  1                   0   
97   -1.00  0.67                  1                   1   
98   -1.00  0.64                  1                   0   
99   -1.00  0.69                  0                   1   

    Surgical Intervention  High fevers in last year  \
0                       1                         0   
1                       1                         0   
2                       0                         0   
3                       1                         0   
4                       0                         0   
..                    ...                       ...   
95                      0                         0   
96                      0                         0   
97                      1                         0   
98                      1                         0   
99                      1                         0   

    Frequency of alcohol consumption  Smoking habit  \
0                                0.8              0   
1                                0.8              1   
2                                1.0             -1   
3                                1.0             -1   
4                                0.8             -1   
..                               ...            ...   
95                               1.0             -1   
96                               0.8              0   
97                               1.0             -1   
98                               1.0              0   
99                               0.6             -1   

    Number of hours spent sitting per day Output  
0                                    0.88      N  
1                                    0.31      O  
2                                    0.50      N  
3                                    0.38      N  
4                                    0.50      O  
..                                    ...    ...  
95                                   0.50      N  
96                                   0.50      N  
97                                   0.31      N  
98                                   0.19      N  
99                                   0.19      N  

[100 rows x 10 columns]

In [3]:
df.shape

(100, 10)

In [4]:
df.size

1000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                                 Non-Null Count  Dtype  
---  ------                                 --------------  -----  
 0   Season                                 100 non-null    float64
 1   Age                                    100 non-null    float64
 2   Childish diseases                      100 non-null    int64  
 3   Accident or Trauma                     100 non-null    int64  
 4   Surgical Intervention                  100 non-null    int64  
 5   High fevers in last year               100 non-null    int64  
 6   Frequency of alcohol consumption       100 non-null    float64
 7   Smoking habit                          100 non-null    int64  
 8   Number of hours spent sitting per day  100 non-null    float64
 9   Output                                 100 non-null    object 
dtypes: float64(4), int64(5), object(1)
memory usage: 7.9+ KB


In [6]:
df.describe(include='all')

Season         Age  Childish diseases  Accident or Trauma  \
count   100.000000  100.000000         100.000000          100.000000   
unique         NaN         NaN                NaN                 NaN   
top            NaN         NaN                NaN                 NaN   
freq           NaN         NaN                NaN                 NaN   
mean     -0.078900    0.669000           0.870000            0.440000   
std       0.796725    0.121319           0.337998            0.498888   
min      -1.000000    0.500000           0.000000            0.000000   
25%      -1.000000    0.560000           1.000000            0.000000   
50%      -0.330000    0.670000           1.000000            0.000000   
75%       1.000000    0.750000           1.000000            1.000000   
max       1.000000    1.000000           1.000000            1.000000   

        Surgical Intervention  High fevers in last year  \
count              100.000000                100.000000   
unique                    NaN                       NaN   
top                       NaN                       NaN   
freq                      NaN                       NaN   
mean                 0.510000                  0.190000   
std                  0.502418                  0.580752   
min                  0.000000                 -1.000000   
25%                  0.000000                  0.000000   
50%                  1.000000                  0.000000   
75%                  1.000000                  1.000000   
max                  1.000000                  1.000000   

        Frequency of alcohol consumption  Smoking habit  \
count                         100.000000     100.000000   
unique                               NaN            NaN   
top                                  NaN            NaN   
freq                                 NaN            NaN   
mean                            0.832000      -0.350000   
std                             0.167501       0.808728   
min                             0.200000      -1.000000   
25%                             0.800000      -1.000000   
50%                             0.800000      -1.000000   
75%                             1.000000       0.000000   
max                             1.000000       1.000000   

        Number of hours spent sitting per day Output  
count                              100.000000    100  
unique                                    NaN      2  
top                                       NaN      N  
freq                                      NaN     88  
mean                                 0.406800    NaN  
std                                  0.186395    NaN  
min                                  0.060000    NaN  
25%                                  0.250000    NaN  
50%                                  0.380000    NaN  
75%                                  0.500000    NaN  
max                                  1.000000    NaN

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
enc = LabelEncoder()

In [9]:
df['Output'] = enc.fit_transform(df['Output'])

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x = df.drop(columns=['Output'])
y = df['Output']

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
log = LogisticRegression()

In [15]:
log.fit(x_train, y_train)

LogisticRegression()

In [16]:
log.score(x_train, y_train)

0.875

In [17]:
log.coef_

array([[ 0.87096524,  0.50576636,  0.1252741 , -0.9847845 ,  0.79489374,
        -0.05639002, -0.4568799 ,  0.39335472, -0.13863498]])

In [18]:
weight_table = pd.DataFrame(columns=['field', 'weight'])

weight_table['field'] = x.columns
weight_table['weight'] = log.coef_[0]

In [19]:
weight_table

field    weight
0                                 Season  0.870965
1                                    Age  0.505766
2                      Childish diseases  0.125274
3                     Accident or Trauma -0.984785
4                  Surgical Intervention  0.794894
5               High fevers in last year -0.056390
6       Frequency of alcohol consumption -0.456880
7                          Smoking habit  0.393355
8  Number of hours spent sitting per day -0.138635

In [20]:
from sklearn.metrics import accuracy_score

In [21]:
y_pred = log.predict(x_test)

y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
accuracy_score(y_test, y_pred)

0.9

In [23]:
from sklearn.naive_bayes import GaussianNB

In [24]:
gnb = GaussianNB()

In [25]:
gnb.fit(x_train, y_train)

GaussianNB()

In [26]:
gnb.score(x_train, y_train)

0.9125

In [28]:
y_pred = gnb.predict(x_test)

y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
accuracy_score(y_test, y_pred)

0.9